project:
  type: website
  output-dir: docs
  execute-dir: project
  render: 
    - "*.qmd"
    - "!templates/"
website:
  title: "Jo's #tidytuesday"
  navbar:
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        href: https://github.com/JoDudding/tidytuesday-jo
      - icon: linkedin
        href: https://www.linkedin.com/in/jo-dudding-18bbaa16/

format:
  html:
    theme: pulse
    #css: assets/styles.css
    toc: true
    embed-resources: true
    fig-cap-location: margin
    tbl-cap-location: margin

execute:     
  echo: false
  message: false
  warning: false
  freeze: auto

knitr:
  opts_chunk:
    dev: "ragg_png"   

date-format: iso  