---
title: "tidytuesday-jo"
format: html
listing: 
  type: default
  contents: weeks
---

```{r}
#| label: setup
#| file: scripts/_setup.r

```

Website for my [#tidytuesday](https://github.com/rfordatascience/tidytuesday) experiments, playing with different data and packages.


::: {.callout-note}
## TODO

Currently working on the setup

- Make charts fit the space
- Github pages

:::


```{r}
#| label: fig-penguin-hist
#| fig-cap: Palmer penguins species flipper length
#| echo: false
#| eval: false

penguins |> 
  filter(! is.na(flipper_len)) |> 
  ggplot(aes(flipper_len)) +
  geom_histogram(binwidth = 3) +
  facet_wrap(~species, ncol = 1) +
  scale_y_c() +
  labs(
    x = "Flipper length",
    y = "Count",
    title = "Gentoo penguins have the longest flippers",
    subtitle = "Distribution of flipper length by penguin species",
    caption = "Source: Palmer Penguins"
  )

```


```{r}
#| label: fig-penguin-scatter
#| fig-cap: Palmer penguins species flipper length by bill length
#| echo: false
#| eval: false

penguins |> 
  filter(
    ! is.na(flipper_len),
    ! is.na(bill_len)
  ) |> 
  ggplot(aes(flipper_len, bill_len, colour = species)) +
  geom_point() +
  scale_x_continuous(label = comma) +
  scale_y_continuous(label = comma) +
  scale_colour_pulse() +
  labs(
    x = "Flipper length",
    y = "Bill length",
    colour = NULL,
    #title = "There are distinct clusters for the different species",
    subtitle = "Flipper length vs bill length by penguin species",
    caption = "Source: Palmer Penguins"
  )

```



